# workaround

image: concourse/concourse
# imageTag: "5.8.1"

secrets:
  localUsers: admin:admin,guest:guest

web:
  replicas: 1
  localAuth:
    enabled: true
  additionalVolumes:
    - name: dsdsocket
      hostPath:
        path: /var/run/datadog
  additionalVolumeMounts:
    - name: dsdsocket
      mountPath: /var/run/datadog

worker:
  replicas: 2
  hardAntiAffinity: true

concourse:
  web:
    auth:
      mainTeam:
        localUser: admin
    metrics:
      attribute: "environment:workaround"
    datadog:
      enabled: true
      agentHost: unix
      agentPort: ///var/run/datadog/dsd.socket
      prefix: "concourse.workaround"
    # externalUrl: https://workaround.concourse-ci.org
    containerPlacementStrategy: fewest-build-containers
    service:
      api: 
        type: NodePort
  worker:
    baggageclaim:
      driver: overlay
datadog:
  datadog:
    useDogStatsDSocketVolume: true
    apiKey: DATADOG_API_KEY
    appKey: DATADOG_APP_KEY
    processAgentEnabled: true
    tags:
      - "env:workaround"
    kubeStateMetrics:
      enabled: false


postgresql:
  postgresqlConfiguration: {"sharedPreloadLibraries": "'pg_stat_statements'", "listenAddresses": "'*'"}
  postgresqlUsername: "concourse"
  postgresqlPassword: "concourse"
  postgresqlPostgresPassword: A_PASSWORD
  # persistence:
  #   size: 16Gi
  # shmVolume:
  #   enabled: true
