# concourse-icg

image: concourse/concourse
imageTag: "5.8.1"

secrets:
  localUsers: admin:admin,guest:guest

web:
  replicas: 2
  localAuth: 
    enabled: true
  additionalVolumes:
    - name: dsdsocket
      hostPath:
        path: /var/run/datadog
  additionalVolumeMounts:
    - name: dsdsocket
      mountPath: /var/run/datadog

worker:
  replicas: 10

concourse:
  web:
    auth:
      mainTeam:
        localUser: admin
    metrics:
      attribute: "environment:cheetara"
    datadog:
      enabled: true       
      agentHost: unix
      agentPort: ///var/run/datadog/dsd.socket
      prefix: "concourse.loadtest"

datadog:
  datadog:
    useDogStatsDSocketVolume: true
    apiKey: DATADOG_API_KEY
    appKey: DATADOG_APP_KEYs
    processAgentEnabled: true
    tags:
      - "env:cheetara"
    kubeStateMetrics:
      enabled: false


postgresql:
  persistence:
    size: 2Gi
